# Generated by Django 5.1.6 on 2025-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsplit',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
