# Generated by Django 5.1.6 on 2025-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupsplit_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseshare',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
