# Generated by Django 5.1.6 on 2025-04-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_split'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Split',
        ),
    ]
